FROM ubuntu:latest

RUN apt-get update && apt-get install --no-install-recommends -y python python-pip python-pycurl openssl python-setuptools \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip install pyresttest future

WORKDIR /app
ADD test/test-api.yaml /app/test-api.yaml
